on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "huguestennier/ab-newstack"
          source_branch: "master"
          destination_repo: "huguestennier/ab-newstack"
          destination_branch: "pricing-b"